services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
